### ISSUE TITLE
Changing how the client is initialized

### ISSUE THREAD

**Issue by treebee** [joshnuss/gotrue-elixir#2]
It would be nice (or even necessary) if another library or application could pass the connection info (url + api_key) to the client initialization.

The Elixir docs even discourage using `Application config` in libraries 
* https://hexdocs.pm/elixir/master/library-guidelines.html#avoid-application-configuration
* https://hexdocs.pm/elixir/master/library-guidelines.html#avoid-compile-time-application-configuration

Maybe something like
```elixir
def client(base_url, api_key, options) do
  access_token = Keyword.get(options, :access_token, api_key)
  middlewares = [
      {Tesla.Middleware.BaseUrl, @base_url},
      Tesla.Middleware.JSON,
      {Tesla.Middleware.Headers, [{:apikey, @api_key}, {:authorization, access_token}]}
    ]
  Tesla.client(middlewares)
  
  # changing functions to get client as first argument
  def update_user(client, info) do
    ...
```

Another option would be always creating the client with only the
base_url and api_key and then overwrite the headers in the module functions

```elixir
def update_user(client, access_token, info) do
  # ... overwrite headers in client ...
  # go on
```  

And then in another library or application it could be used like
```elixir
GoTrue.client(my_base_url, my_api_key)
|> GoTrue.update_user(access_token, %{"username" => "new-user-name"})
```

**Comment by joshnuss** [comment]
Yes, I agree. Making the client too dependant on config could make it harder to use. Especially in multi-tenant systems.

I wonder if there is a way to support both scenarios. Like two constructor functions, ie `client` and `client_from_config`

For setting user specific stuff, what do you think about following the same pattern as supabase-js, ie:

```
client(url, api_key)
|> with_session(access_token)
|> update_user(...)
```

**Comment by treebee** [comment]
> I wonder if there is a way to support both scenarios. Like two constructor functions, ie `client` and `client_from_config`
> 
We wouldn't even need two differently named functions, we could use two with different arity:

```elixir
def client() do
  url = Application.fetch_env!(:gotrue, :base_url)
  api_key = Application.fetch_env!(:gotrue, :api_key)
  client(url, api_key)
end

def client(url, api_key) do
  ...
end
```


> For setting user specific stuff, what do you think about following the same pattern as supabase-js, ie:
> 
> ```
> client(url, api_key)
> |> with_session(access_token)
> |> update_user(...)
> ```

Is this really how supabase-js does it? To me it looks like it would be
```elixir
client(url, api_key)
|> update_user(access_token, ...)
```
see here https://github.com/supabase/supabase-js/blob/master/src/SupabaseClient.ts#L147
and here https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L237

For me this also feels a bit more intuitive, having an operation `update_user` saying "I need  a valid `access_token` with enough permissions to execute the operation". Would also be more consistent with the APIs of the other clients, like `gotrue-js`, `gotrue-py` (for example https://github.com/supabase/gotrue-py/blob/main/gotrue/api.py#L178) etc.

**Comment by treebee** [comment]
I created a PR implementing what I meant.

**Comment by joshnuss** [comment]
Good points,

Thanks Patrick, I'll take a look now.

**Comment by joshnuss** [comment]
PR is merged, so closing.

Thanks again!
